### ISSUE TITLE
Grabbing license data with object method, but it's an array

### ISSUE THREAD

**Issue by joelworsham** [realbigplugins/rbp-support#10]
![](http://d.pr/i/h3izeh+)

**Comment by d4mation** [comment]
So, oddly enough on a fresh implementation of RBP_Support it is wanting that to be an Object rather than an Array in the exact same spot: In the email code 😐 

```
Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /srv/www/edd/htdocs/wp-content/plugins/psp-edd/includes/rbp-support/rbp-support.php:1334 Stack trace: #0 /srv/www/edd/htdocs/wp-includes/class-wp-hook.php(298): RBP_Support->send_support_email('') #1 /srv/www/edd/htdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #2 /srv/www/edd/htdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /srv/www/edd/htdocs/wp-admin/admin.php(154): do_action('admin_init') #4 /srv/www/edd/htdocs/wp-admin/options-general.php(10): require_once('/srv/www/edd/ht...') #5 {main} thrown in /srv/www/edd/htdocs/wp-content/plugins/psp-edd/includes/rbp-support/rbp-support.php on line 1334
```

**Comment by d4mation** [comment]
Although after forcing the Transient to be deleted it worked….?

I wonder if it was because before I had a valid License I had an invalid one and that one saved junk in the transient? Going to need more investigation.

**Comment by d4mation** [comment]
Of course, now I can't replicate it.

I can't see anything wrong with your code, @joelworsham, so I have 0 clue why it happened at all. Going to re-close.

**Comment by d4mation** [comment]
Actually, I think know why. Because #5.

I had a plugin using an older version of RBP_Support active and it is higher in the list alphabetically so it loaded its copy and that must have been when I saved the data as an Object. Once I went to test the Email code, I had already deactivated that other plugin.

**Comment by joelworsham** [comment]
Ohhh perhaps we should typecase the license data just to be safe?

**Comment by d4mation** [comment]
Typecasting wouldn't be a bad idea. This is a little bit edge-case since it requires Plugin Activation/Deactivation at the wrong moments. But it could happen. Typecasting would help ensure that this doesn't happen.
