### ISSUE TITLE
Delete and Deactivate only deactives

### ISSUE THREAD

**Issue by joelworsham** [realbigplugins/rbp-support#11]
1. Active license
2. Click "Delete and Deactivate"

Expected: License is deactivated and completely removed.
Actual: License is deactivated but not deleted. Still saved.

**Comment by joelworsham** [comment]
Actually, interestingly, after clicking "Delete and Deactivate", it only showed that it was deactivated, but it still showed in the license field. I then clicked "Activate", and then got the error message "Invalid license" and the license is now gone.

So it seems the license did delete but:

A. It didn't reflect on initial page load after deleting
B. There was no success message indicating it was deleted, only that it was deactivated.

**Comment by joelworsham** [comment]
Here's a short screencast for added clarity:

![](http://d.pr/i/XQKmW3+)

**Comment by d4mation** [comment]
Oh, weird. Might be some timing issue. Good catch!

**Comment by d4mation** [comment]
So, turns out this is due to the speed and timing of which `wp_options` updates. I ended up correcting this by just not getting the value from the database if the action was to delete the key since the deletion was going through properly anyway :+1:
