### ISSUE TITLE
Add ability to use Download ID rather than Plugin Name for Licensing

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/rbp-support#17]
I personally like using Plugin Name since it doesn't get Localized and we normally shouldn't have a different Download Name and Plugin Name.

However, maybe a Filter should be added for those edge-cases where using a Download ID makes sense? This would allow it to find the correct Download no matter what the Plugin Name is.

**Comment by joelworsham** [comment]
Coudln't hurt to have the option
