### ISSUE TITLE
If WP_DEBUG and WP_DEBUG_LOG are set, allow option to attach debug.log

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/rbp-support#19]
This could be immensely helpful, but I don't feel right doing this without approval from the customer.

A simple checkbox added to the Form saying that it will send debugging information and only showing that checkbox if `WP_DEBUG` and `WP_DEBUG_LOG` are set should be sufficient.

**Comment by d4mation** [comment]
Actually, this may not even be possible as `debug.log` could potentially be hundreds of megabytes or even be a few gigabytes long depending on how long it has been running with errors present.

**Comment by joelworsham** [comment]
Yeahhhhh :/

**Comment by d4mation** [comment]
It was a cool idea though ¯\\\_(ツ)_/¯
