### ISSUE TITLE
Stop using EDD-License-handler as a sub module.

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/rbp-support#36]
It still works for now as it pulls a commit from before they nuked the Repo, but it would probably be best to grab this another way.

@joelworsham, do you have access to https://github.com/easydigitaldownloads/EDD-Software-Licensing ? If so, I may just sub module that to be honest and use the Gulp script to remove all the other files on build. I'd prefer to not have to need to track this file in the repo itself.

**Comment by joelworsham** [comment]
I do not have access :(

**Comment by BigActual** [comment]
@brashrebel can you help Eric submodule this?

**Comment by d4mation** [comment]
Since Joel no longer needs access, I can technically submodule it myself as I have access to the Repo. But anyone else we may bring in in the future on any sort of basis would be incapable of accessing that data by default as it is a Private Repo.

**Comment by d4mation** [comment]
I no longer have access to this myself, so submodule is out of the question.

I'm thinking that instead, these methods should be written ourselves. I've been tinkering with getting Changelogs to display from GitHub directly (even when the Repo is Private) and it turns out that some aspects of what is written in there actually doesn't work with modern WP anymore. The important stuff like License Activation/Deactivation/etc. does, but there's some other nice bits of functionality in there that's straight up dormant.
